platform :ios,'8.0'
use_frameworks!
target 'ProjectSummary' do 
pod 'ReactiveCocoa','4.0'
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'Masonry'
pod 'MBProgressHUD'
end
